name: chitchat_02
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  appwrite: ^12.0.1
#  firebase_core: ^2.27.2
#  cloud_firestore: ^4.15.10
#  firebase_auth: ^4.18.0
#  firebase_crashlytics: ^3.4.20
#  firebase_performance: ^0.9.3+19



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    - images/


